// ESP32 pin definitions
const esp32Pins = {
    0: { name: 'GPIO0', type: 'Boot/Flash', capabilities: ['Digital I/O', 'PWM', 'Boot Pin'] },
    1: { name: 'GPIO1/TX0', type: 'UART', capabilities: ['UART TX', 'Digital I/O'] },
    2: { name: 'GPIO2', type: 'Boot/Flash', capabilities: ['Digital I/O', 'PWM', 'Boot Pin', 'LED'] },
    3: { name: 'GPIO3/RX0', type: 'UART', capabilities: ['UART RX', 'Digital I/O'] },
    4: { name: 'GPIO4', type: 'Digital', capabilities: ['Digital I/O', 'PWM', 'Touch'] },
    5: { name: 'GPIO5', type: 'Digital', capabilities: ['Digital I/O', 'PWM', 'SPI CS'] },
    12: { name: 'GPIO12', type: 'Touch', capabilities: ['Digital I/O', 'PWM', 'Touch', 'ADC2'] },
    13: { name: 'GPIO13', type: 'Touch', capabilities: ['Digital I/O', 'PWM', 'Touch', 'ADC2'] },
    14: { name: 'GPIO14', type: 'Touch', capabilities: ['Digital I/O', 'PWM', 'Touch', 'ADC2'] },
    15: { name: 'GPIO15', type: 'Touch', capabilities: ['Digital I/O', 'PWM', 'Touch', 'ADC2'] },
    16: { name: 'GPIO16/RX2', type: 'UART', capabilities: ['UART RX', 'Digital I/O', 'PWM'] },
    17: { name: 'GPIO17/TX2', type: 'UART', capabilities: ['UART TX', 'Digital I/O', 'PWM'] },
    18: { name: 'GPIO18/SCK', type: 'SPI', capabilities: ['SPI SCK', 'Digital I/O', 'PWM'] },
    19: { name: 'GPIO19/MISO', type: 'SPI', capabilities: ['SPI MISO', 'Digital I/O', 'PWM'] },
    21: { name: 'GPIO21/SDA', type: 'I2C', capabilities: ['I2C SDA', 'Digital I/O', 'PWM'] },
    22: { name: 'GPIO22/SCL', type: 'I2C', capabilities: ['I2C SCL', 'Digital I/O', 'PWM'] },
    23: { name: 'GPIO23/MOSI', type: 'SPI', capabilities: ['SPI MOSI', 'Digital I/O', 'PWM'] },
    25: { name: 'GPIO25', type: 'Analog', capabilities: ['Digital I/O', 'PWM', 'DAC1', 'ADC2'] },
    26: { name: 'GPIO26', type: 'Analog', capabilities: ['Digital I/O', 'PWM', 'DAC2', 'ADC2'] },
    27: { name: 'GPIO27', type: 'Touch', capabilities: ['Digital I/O', 'PWM', 'Touch', 'ADC2'] },
    32: { name: 'GPIO32', type: 'Touch', capabilities: ['Digital I/O', 'PWM', 'Touch', 'ADC1'] },
    33: { name: 'GPIO33', type: 'Touch', capabilities: ['Digital I/O', 'PWM', 'Touch', 'ADC1'] },
    34: { name: 'GPIO34', type: 'Input Only', capabilities: ['Analog Input', 'ADC1'] },
    35: { name: 'GPIO35', type: 'Input Only', capabilities: ['Analog Input', 'ADC1'] },
    36: { name: 'GPIO36/VP', type: 'Input Only', capabilities: ['Analog Input', 'ADC1'] },
    39: { name: 'GPIO39/VN', type: 'Input Only', capabilities: ['Analog Input', 'ADC1'] }
};
